app:
  api:
    title: @artifactId@
    version: @version@
    description: @description@
    base-package: com.adidas.subscription
    contact-name: Borja
    contact-email: borjacolmenarejo@gmail.com

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
    validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2

adidas:
  service:
    email:
      url: http://localhost:8081